# Generated by Django 3.2.6 on 2021-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BinaryField()),
                ('A1', models.BinaryField()),
                ('A2', models.BinaryField()),
                ('B1', models.BinaryField()),
                ('B2', models.BinaryField()),
                ('C1', models.BinaryField()),
                ('C2', models.BinaryField()),
                ('D', models.BinaryField()),
            ],
        ),
    ]
